import type { Config } from "tailwindcss";
import defaultTheme from "tailwindcss/defaultTheme";

/**
 * QueryPro AI — Design Tokens (v2, dark-mode-native)
 * ----------------------------------------------------------------------------
 * Phase 1 of the premium redesign. Two real themes — dark (default) and
 * light — driven by CSS custom properties defined in globals.css, so a
 * single `<html class="light">` toggle re-skins the whole app.
 *
 * A token is either:
 *  - Theme-reactive: defined as `rgb(var(--color-x) / <alpha-value>)`,
 *    resolved from `:root` (dark) or `.light` (light) in globals.css.
 *  - Theme-invariant: a plain hex value, used only on surfaces that stay
 *    dark regardless of theme (code blocks, the nav drawer) — per the
 *    original design rule that utility/technical surfaces are always dark.
 *
 * UI DENSITY SCALE — 2026-07-27
 * ----------------------------------------------------------------------------
 * The whole app's density is scaled to `UI_SCALE` of its original size from
 * this single spot. Tailwind's base `spacing` and `fontSize` scales are
 * overridden (not `extend`-ed) with every value multiplied by UI_SCALE, and
 * this app's own named tokens (`extend.spacing`, `extend.fontSize`,
 * `extend.borderRadius`) are scaled the same way. Because the whole codebase
 * consistently builds on these scales, every `h-*`, `w-*`, `p-*`, `m-*`,
 * `gap-*`, `text-*`, `max-w-*`, `rounded-*` utility across every page shrinks
 * together automatically — no component files needed to change for anything
 * built on the theme scale. The only things scaled by hand at their call
 * sites were arbitrary bracket values (e.g. `h-[18px]`) and `clamp()`/
 * `shadow-[...]` expressions, which bypass the theme scale entirely.
 */
const UI_SCALE = 0.75;

/** Scales a single "<number><unit>" string (rem/px/em) by `factor`. */
function scaleUnit(value: string, factor: number): string {
  const match = /^(-?[\d.]+)(rem|px|em)$/.exec(value.trim());
  if (!match) return value;
  const num = match[1];
  const unit = match[2];
  if (!num || !unit) return value;
  const scaled = Math.round(parseFloat(num) * factor * 10000) / 10000;
  return `${scaled}${unit}`;
}

/** Scales every value in a flat spacing-style scale object. */
function scaleSpacingScale(source: Record<string, string>, factor: number) {
  return Object.fromEntries(Object.entries(source).map(([key, value]) => [key, scaleUnit(value, factor)]));
}

type FontSizeEntry = string | [string, { lineHeight?: string; letterSpacing?: string; fontWeight?: string }];

/**
 * Scales a fontSize scale object. Only the size itself and `lineHeight` are
 * scaled — `letterSpacing` is deliberately left untouched because it's
 * already expressed in `em` in this scale, which is relative to font-size
 * and therefore scales automatically as the size shrinks. `fontWeight`
 * isn't a dimension.
 */
function scaleFontSizeScale(source: Record<string, FontSizeEntry>, factor: number) {
  return Object.fromEntries(
    Object.entries(source).map(([key, value]) => {
      if (Array.isArray(value)) {
        const [size, opts] = value;
        const scaledOpts = { ...opts };
        const lineHeight = opts.lineHeight;
        if (lineHeight) scaledOpts.lineHeight = scaleUnit(lineHeight, factor);
        return [key, [scaleUnit(size, factor), scaledOpts]];
      }
      return [key, scaleUnit(value, factor)];
    })
  );
}

// Tailwind's default `maxWidth` scale is generated by a function internally
// and isn't exported statically from `tailwindcss/defaultTheme`, so its
// stable, documented rem values are reproduced here to scale them the same
// way as everything else. Keyword/relative entries (full, min, max, fit,
// prose, none) are left untouched — they aren't literal dimensions.
const DEFAULT_MAX_WIDTH: Record<string, string> = {
  none: "none",
  xs: "20rem",
  sm: "24rem",
  md: "28rem",
  lg: "32rem",
  xl: "36rem",
  "2xl": "42rem",
  "3xl": "48rem",
  "4xl": "56rem",
  "5xl": "64rem",
  "6xl": "72rem",
  "7xl": "80rem",
  full: "100%",
  min: "min-content",
  max: "max-content",
  fit: "fit-content",
  prose: "65ch",
};

function scaleMaxWidthScale(source: Record<string, string>, factor: number) {
  return Object.fromEntries(
    Object.entries(source).map(([key, value]) => [key, /^-?[\d.]+rem$/.test(value) ? scaleUnit(value, factor) : value])
  );
}

/** Scales every bare `<number>px` found inside a multi-part shadow string, leaving rgba(...) color numbers untouched. */
function scaleShadow(value: string, factor: number): string {
  return value.replace(/(-?\d+(?:\.\d+)?)px/g, (_, num) => `${Math.round(parseFloat(num) * factor)}px`);
}

function themeColor(name: string) {
  return `rgb(var(--color-${name}) / <alpha-value>)`;
}

const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{ts,tsx}",
    "./src/components/**/*.{ts,tsx}",
  ],
  theme: {
    // Overriding (not extending) these three so every utility built on
    // Tailwind's core scale resolves at UI_SCALE app-wide. See the note
    // above.
    spacing: scaleSpacingScale(defaultTheme.spacing as Record<string, string>, UI_SCALE),
    fontSize: scaleFontSizeScale(defaultTheme.fontSize as Record<string, FontSizeEntry>, UI_SCALE),
    maxWidth: scaleMaxWidthScale(DEFAULT_MAX_WIDTH, UI_SCALE),
    extend: {
      colors: {
        // --- Theme-reactive (main canvas) ---
        background: themeColor("background"),
        surface: themeColor("background"),
        "surface-container-lowest": themeColor("surface-container-lowest"),
        "surface-container-low": themeColor("surface-container-low"),
        "surface-container": themeColor("surface-container"),
        "surface-container-high": themeColor("surface-container-high"),
        "surface-container-highest": themeColor("surface-container-highest"),
        "surface-variant": themeColor("surface-container-highest"),

        "on-background": themeColor("on-surface"),
        "on-surface": themeColor("on-surface"),
        "on-surface-variant": themeColor("on-surface-variant"),
        "brand-dark": themeColor("on-surface"),

        outline: themeColor("outline"),
        "outline-variant": themeColor("outline-variant"),
        "border-subtle": themeColor("border-subtle"),

        primary: themeColor("primary"),
        "primary-container": themeColor("primary-container"),
        "on-primary": themeColor("on-primary"),
        "on-primary-container": themeColor("on-primary-container"),

        secondary: themeColor("secondary"),
        "secondary-container": themeColor("secondary-container"),
        "on-secondary": themeColor("on-secondary"),
        "on-secondary-container": themeColor("on-secondary-container"),

        "accent-ai": themeColor("accent-ai"),

        tertiary: themeColor("tertiary"),
        "tertiary-container": themeColor("tertiary-container"),
        "on-tertiary": themeColor("on-primary"),

        success: themeColor("success"),
        "success-container": themeColor("success-container"),
        "on-success": themeColor("on-primary"),

        error: themeColor("error"),
        "on-error": themeColor("on-primary"),
        "error-container": themeColor("error-container"),
        "on-error-container": themeColor("on-error-container"),

        // --- Theme-invariant utility surfaces (always-dark by design) ---
        // Now driven by CSS custom properties so light mode can use a softer
        // dark-navy tone instead of the full deep-#0a0e18 which reads as a
        // broken black box on a light canvas.
        "inverse-surface": "#0a0e18",
        "inverse-on-surface": "#dfe2f1",
        "code-bg": themeColor("code-bg"),
        "code-bg-header": themeColor("code-bg-header"),
        "code-gutter": themeColor("code-gutter"),
        "primary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#b2c5ff",
        "tertiary-fixed-dim": "#ffc97a",
        "drawer-border": "#1E293B",

        // --- SQL syntax highlighting (exact hex from the mockups) ---
        "syntax-keyword": "#4680FF",
        "syntax-string": "#10B981",
        "syntax-comment": "#64748B",
        "syntax-function": "#FBBF24",
        "warning-amber": "#E58A00",
      },
      borderRadius: {
        sm: scaleUnit("0.25rem", UI_SCALE),
        DEFAULT: scaleUnit("0.5rem", UI_SCALE),
        md: scaleUnit("0.75rem", UI_SCALE),
        lg: scaleUnit("1rem", UI_SCALE),
        xl: scaleUnit("1.5rem", UI_SCALE),
        full: "9999px",
      },
      spacing: scaleSpacingScale(
        {
          base: "8px",
          xs: "4px",
          sm: "12px",
          md: "16px",
          lg: "24px",
          xl: "32px",
          "2xl": "48px",
          gutter: "24px",
          "sidebar-width": "260px",
          "drawer-width": "320px",
          "container-max": "1440px",
        },
        UI_SCALE
      ),
      maxWidth: {
        "container-max": scaleUnit("1440px", UI_SCALE),
        "drawer-width": scaleUnit("320px", UI_SCALE),
      },
      fontFamily: {
        sans: ["var(--font-public-sans)", "sans-serif"],
        heading: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-jetbrains-mono)", "monospace"],
      },
      fontSize: scaleFontSizeScale(
        {
          "display-lg": [
            "48px",
            { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" },
          ],
          "headline-xl": [
            "32px",
            { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" },
          ],
          "headline-xl-mobile": [
            "28px",
            { lineHeight: "36px", fontWeight: "600" },
          ],
          "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
          "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
          "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
          "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
          "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
          "label-md": ["13px", { lineHeight: "16px", fontWeight: "500" }],
          "label-sm": [
            "11px",
            { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" },
          ],
        },
        UI_SCALE
      ),
      boxShadow: {
        "elevation-1": scaleShadow(
          "0 1px 3px 0 rgba(0, 0, 0, 0.24), 0 1px 2px 0 rgba(0, 0, 0, 0.18)",
          UI_SCALE
        ),
        "elevation-2": scaleShadow("0 8px 24px -4px rgba(0, 0, 0, 0.36)", UI_SCALE),
        "elevation-3": scaleShadow("0 20px 48px -12px rgba(0, 0, 0, 0.5)", UI_SCALE),
        "focus-ring": scaleShadow("0 0 0 3px rgba(91, 141, 255, 0.25)", UI_SCALE),
        drawer: scaleShadow("12px 0 32px -8px rgba(0, 0, 0, 0.5)", UI_SCALE),
      },
      keyframes: {
        "pulse-ring": {
          "0%": { boxShadow: scaleShadow("0 0 0 0px rgba(52, 211, 153, 0.4)", UI_SCALE) },
          "100%": { boxShadow: scaleShadow("0 0 0 8px rgba(52, 211, 153, 0)", UI_SCALE) },
        },
        "fade-in": {
          from: { opacity: "0", transform: `translateY(${scaleUnit("4px", UI_SCALE)})` },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "drawer-in": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "drawer-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "backdrop-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.97)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        ripple: {
          from: { transform: "scale(0)", opacity: "0.5" },
          to: { transform: "scale(1)", opacity: "0" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 2s infinite",
        "fade-in": "fade-in 0.2s ease-out",
        "drawer-in": "drawer-in 0.28s cubic-bezier(0.16, 1, 0.3, 1)",
        "drawer-in-right": "drawer-in-right 0.28s cubic-bezier(0.16, 1, 0.3, 1)",
        "backdrop-in": "backdrop-in 0.2s ease-out",
        "scale-in": "scale-in 0.15s cubic-bezier(0.16, 1, 0.3, 1)",
        ripple: "ripple 0.6s ease-out",
      },
      transitionProperty: {
        height: "height",
      },
    },
  },
  plugins: [],
};

export default config;
